export const VIETNAM_CITIES = [
  "Hà Nội",
  "Hồ Chí Minh",
  "Hải Phòng",
  "Đà Nẵng",
  "Huế",
  "Cần Thơ",

  "Cao Bằng",
  "Lai Châu",
  "Điện Biên",
  "Sơn La",
  "Lạng Sơn",
  "Quảng Ninh",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",

  "Tuyên Quang",
  "Lào Cai",
  "Thái Nguyên",
  "Phú Thọ",
  "Bắc Ninh",
  "Hưng Yên",
  "Ninh Bình",

  "Quảng Trị",
  "Quảng Ngãi",
  "Gia Lai",
  "Khánh Hòa",
  "Lâm Đồng",
  "Đồng Nai",
  "Tây Ninh",

  "Đồng Tháp",
  "Vĩnh Long",
  "An Giang",
  "Cà Mau"
];

export const COUNTRIES = [
  "Việt Nam",
  "Hoa Kỳ",
  "Vương quốc Anh",
  "Anh",
  "Pháp",
  "Đức",
  "Nhật Bản",
  "Hàn Quốc",
  "Trung Quốc",
  "Hồng Kông",
  "Thái Lan",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Úc",
  "Canada",
  "Ấn Độ",
  "Tây Ban Nha",
  "Ý",
  "Nga",
  "Brazil",
  "Mexico",
  "Hà Lan",
  "Bỉ",
  "Thụy Sĩ",
  "Thụy Điển",
  "Na Uy",
  "Đan Mạch",
  "Phần Lan",
  "Ba Lan",
  "Thổ Nhĩ Kỳ",
  "Argentina",
  "Nam Phi",
  "Quốc gia khác",
];

// 🌍 Map mã quốc gia TMDB theo tiêu chuẩn ISO 3166-1
export const COUNTRY_MAP = {
  "VN": "Việt Nam",
  "US": "Hoa Kỳ",
  "GB": "Anh",
  "FR": "Pháp",
  "DE": "Đức",
  "JP": "Nhật Bản",
  "KR": "Hàn Quốc",
  "CN": "Trung Quốc",
  "TH": "Thái Lan",
  "SG": "Singapore",
  "MY": "Malaysia",
  "ID": "Indonesia",
  "PH": "Philippines",
  "AU": "Úc",
  "CA": "Canada",
  "IN": "Ấn Độ",
  "ES": "Tây Ban Nha",
  "IT": "Ý",
  "RU": "Nga",
  "BR": "Brazil",
  "MX": "Mexico",
  "NL": "Hà Lan",
  "CH": "Thụy Sĩ",
  "SE": "Thụy Điển",
  "NO": "Na Uy",
  "DK": "Đan Mạch",
  "FI": "Phần Lan",
  "PL": "Ba Lan",
  "TR": "Thổ Nhĩ Kỳ",
  "AR": "Argentina",
  "ZA": "Nam Phi",
  "NZ": "New Zealand",
  "NG": "Nigeria",
  "PK": "Pakistan",
  "BD": "Bangladesh",
  "TW": "Đài Loan",
  "HK": "Hồng Kông",
  "MO": "Macao",
  "KH": "Campuchia",
  "LA": "Lào",
  "MM": "Myanmar",
  "KZ": "Kazakhstan",
  "UZ": "Uzbekistan",
  "AE": "Tiểu vương quốc Ả Rập Thống nhất",
  "SA": "Ả Rập Xê Út",
  "IL": "Israel",
  "UA": "Ukraina",
  "CZ": "Cộng hòa Czech",
  "HU": "Hungary",
  "RO": "Romania",
  "GR": "Hy Lạp",
  "BG": "Bulgaria",
  "HR": "Croatia",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "AT": "Áo",
  "BE": "Bỉ",
  "PT": "Bồ Đào Nha",
  "IE": "Ireland",
  "LU": "Luxembourg",
  "CY": "Cyprus",
  "MT": "Malta",
  "CO": "Colombia",
  "PE": "Peru",
  "CL": "Chile",
  "VE": "Venezuela",
  "EC": "Ecuador",
  "BO": "Bolivia",
  "PY": "Paraguay",
  "UY": "Uruguay",
  "GY": "Guyana",
  "SR": "Suriname",
  "EG": "Ai Cập",
  "KE": "Kenya",
  "ET": "Ethiopia",
  "MA": "Morocco",
  "CI": "Côte d'Ivoire",
  "GH": "Ghana",
};

// 🗣️ Danh sách các ngôn ngữ hợp lệ
export const LANGUAGES = [
  "Tiếng Việt",
  "Tiếng Anh",
  "Tiếng Pháp",
  "Tiếng Đức",
  "Tiếng Tây Ban Nha",
  "Tiếng Nhật",
  "Tiếng Hàn",
  "Tiếng Trung",
  "Tiếng Nga",
  "Tiếng Ý",
  "Tiếng Bồ Đào Nha",
  "Tiếng Hà Lan",
  "Tiếng Ba Lan",
  "Tiếng Thổ Nhĩ Kỳ",
  "Tiếng Thái",
  "Tiếng Indonesia",
  "Tiếng Tagalog",
  "Tiếng Hindi",
  "Tiếng Ả Rập",
  "Tiếng Hebrew",
  "Tiếng Thụy Điển",
  "Tiếng Na Uy",
  "Tiếng Đan Mạch",
  "Tiếng Phần Lan",
  "Tiếng Malayalam",
  "Tiếng Czech",
  "Tiếng Hungary",
  "Tiếng Romania",
  "Tiếng Hy Lạp",
  "Tiếng Bulgaria",
  "Tiếng Croatia",
  "Tiếng Slovakia",
  "Tiếng Slovenia",
  "Tiếng Estonia",
  "Tiếng Latvia",
  "Tiếng Lithuania",
  "Tiếng Ukraina",
  "Tiếng Catalan",
  "Tiếng Wales",
  "Ngôn ngữ khác",
];

// 🌐 Map ngôn ngữ theo mã ISO 639-1
export const LANGUAGE_MAP = {
  "vi": "Tiếng Việt",
  "en": "Tiếng Anh",
  "fr": "Tiếng Pháp",
  "de": "Tiếng Đức",
  "es": "Tiếng Tây Ban Nha",
  "ja": "Tiếng Nhật",
  "ko": "Tiếng Hàn",
  "zh": "Tiếng Trung",
  "ru": "Tiếng Nga",
  "it": "Tiếng Ý",
  "pt": "Tiếng Bồ Đào Nha",
  "nl": "Tiếng Hà Lan",
  "pl": "Tiếng Ba Lan",
  "tr": "Tiếng Thổ Nhĩ Kỳ",
  "th": "Tiếng Thái",
  "id": "Tiếng Indonesia",
  "tl": "Tiếng Tagalog",
  "hi": "Tiếng Hindi",
  "ar": "Tiếng Ả Rập",
  "he": "Tiếng Hebrew",
  "sv": "Tiếng Thụy Điển",
  "no": "Tiếng Na Uy",
  "da": "Tiếng Đan Mạch",
  "fi": "Tiếng Phần Lan",
  "cs": "Tiếng Czech",
  "hu": "Tiếng Hungary",
  "ro": "Tiếng Romania",
  "el": "Tiếng Hy Lạp",
  "bg": "Tiếng Bulgaria",
  "hr": "Tiếng Croatia",
  "sk": "Tiếng Slovakia",
  "sl": "Tiếng Slovenia",
  "et": "Tiếng Estonia",
  "lv": "Tiếng Latvia",
  "lt": "Tiếng Lithuania",
  "uk": "Tiếng Ukraina",
  "ca": "Tiếng Catalan",
  "cy": "Tiếng Wales",
  "ml": "Tiếng Malayalam",
};

